# Capítulo 4: Objetos

Livro: Aprendendo Química com Python, Rodrigo Q. de Albuquerque & Gerd B. da Rocha, 2021, Amazon Book.

E-Mail: learn.chem.python@gmail.com


### Versão do Python usada

In [294]:
import sys
print(sys.version)

3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]


### Caixa de sessão interativa 6: Cadeia de caracteres

In [295]:
a = 'Estude'
b = ' Python!'

In [296]:
a 

'Estude'

In [297]:
3*b

' Python! Python! Python!'

In [298]:
a + b 

'Estude Python!'

In [299]:
c = a + b
c

'Estude Python!'

In [300]:
len(c)     # número total de caracteres (do inglês, length)

14

In [301]:
c[0]

'E'

In [302]:
c[-1]

'!'

In [303]:
c[1:3]     # último índice (= 3) é sempre excluído da seção!

'st'

In [304]:
a.upper()  # método para gerar letras maiúsculas

'ESTUDE'

### Caixa de sessão interativa 7: Listas

In [305]:
a = [10, 'oi', 3.14]   # elementos são separados por vírgulas

In [306]:
a[0]

10

In [307]:
a[2]*2

6.28

In [308]:
a.append('tudo bem')   # adicione mais um elemento à lista
a

[10, 'oi', 3.14, 'tudo bem']

In [309]:
a[0] = 5               # redefina o primeiro elemento
a

[5, 'oi', 3.14, 'tudo bem']

In [310]:
a[1:]                  # segundo elemento em diante

['oi', 3.14, 'tudo bem']

In [311]:
a[:2]          # elementos até índice '2' ('2' nao incluso!)

[5, 'oi']

In [312]:
len(a)

4

In [313]:
a.remove('oi')         # remova elemento 'oi' da lista
a

[5, 3.14, 'tudo bem']

In [314]:
a[0] = [-1,-2,-3]      # primeiro elemento será uma lista!
a

[[-1, -2, -3], 3.14, 'tudo bem']

In [315]:
a[0][1]                # elemento '0', sub-elemento '1'

-2

In [316]:
3.14 in a              # '3.14' é um elemento da lista 'a'?

True

### Caixa de sessão interativa 8: Tuplas

In [317]:
5, 'oi', 3.14      # tupla é criada, mas não é salva

(5, 'oi', 3.14)

In [318]:
a = 5, 'oi', 3.14  # chame a tupla de 'a'
a

(5, 'oi', 3.14)

In [319]:
len(a)

3

In [320]:
a[1]               # segundo elemento de 'a'

'oi'

In [321]:
b = (1,2,3)        # crie outra tupla (com parêntesis)
b

(1, 2, 3)

In [322]:
2 * b              # operações aritméticas (2 * b = b + b)

(1, 2, 3, 1, 2, 3)

In [323]:
c = a + b          # combine tuplas pra criar outra tupla
c

(5, 'oi', 3.14, 1, 2, 3)

In [324]:
v1, v2, v3, v4, v5, v6 = c  # gere novas variáveis

In [325]:
v2

'oi'

In [326]:
v3

3.14

### Caixa de sessão interativa 9: Sets

In [327]:
a = {1, 2, 3}     # crie o set 'a'
len(a)

3

In [328]:
a.add(4)          # adicione o elemento 4 ao set 'a'
a

{1, 2, 3, 4}

In [329]:
a.remove(4)       # remova o elemento 4
a

{1, 2, 3}

In [330]:
b = [3, 4, 4, 5]  # crie a lista 'b'
b = set(b)        # converta 'b' em set
b

{3, 4, 5}

In [331]:
a - b             # remova de 'a' eventuais elementos de 'b'

{1, 2}

In [332]:
a | b           # some os dois sets (sem duplicatas, claro!)

{1, 2, 3, 4, 5}

In [333]:
a & b             # ache a intersecção entre os dois sets

{3}

### Caixa de sessão interativa 10: Dicionários

In [334]:
Z = {'H': 1, 'He': 2, 'Li': 3}       # crie o dicionário

In [335]:
type(Z)                              # tipo do objeto

dict

In [336]:
Z['H']                               # consulte valor
Z['Be'] = 4                          # adicione novo ítem
Z

{'H': 1, 'He': 2, 'Li': 3, 'Be': 4}

In [337]:
Z.pop('Be')                          # remova ítem
Z

{'H': 1, 'He': 2, 'Li': 3}

In [338]:
len(Z)                              # tamanho do dicionário

3

In [339]:
Z.keys()                            # mostre todas as chaves

dict_keys(['H', 'He', 'Li'])

In [340]:
Z.values()                          # mostre todos os valores

dict_values([1, 2, 3])

In [341]:
Z1 = {'H': 1, 'Be': 4}              # crie outro dicionário
Z.update(Z1)                        # insira 'Z1' em 'Z'
Z

{'H': 1, 'He': 2, 'Li': 3, 'Be': 4}

### Caixa de sessão interativa 11: Criação e atributos de variáveis indexadas

In [342]:
import numpy as np     # importe a biblioteca numpy como 'np'
a = [1, 2, 3]          # crie uma lista simples
a = np.array(a)        # converta 'a' numa variável indexada
a

array([1, 2, 3])

In [343]:
a.shape                # atributo: componentes por dimensão

(3,)

In [344]:
b = [[1,2,3],[4,5,6]]  # crie uma lista com 2 sublistas
b = np.array(b)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [345]:
b.shape

(2, 3)

In [346]:
b.size              # numero total de elementos de 'b'

6

In [347]:
b[0,1]              # primeira linha (0), segunda coluna (1)

2

In [348]:
b[1,:]              # segunda linha (1), todas as colunas (:)

array([4, 5, 6])

### Caixa de sessão interativa 12: Métodos de variáveis indexadas

In [ ]:
import numpy as np

In [349]:
b = np.array([[1, 2, 3],[4, 5, 6]])   
b

array([[1, 2, 3],
       [4, 5, 6]])

In [350]:
b.mean()              # média de todos os elementos

3.5

In [351]:
b.mean(axis = 0)      # média de cada coluna

array([2.5, 3.5, 4.5])

In [352]:
b.mean(axis = 1)      # média de cada linha

array([2., 5.])

In [353]:
b.std()                 # desvio padrão de todos os elementos

1.707825127659933

In [354]:
b.std(axis = 1)                 # desvio padrão de cada linha

array([0.81649658, 0.81649658])

In [355]:
b.max(), b.min()             # valores máximo e mínimo de 'b'

(6, 1)

In [356]:
b.reshape(1,6)        # mude a forma para 1 linha e 6 colunas

array([[1, 2, 3, 4, 5, 6]])

In [357]:
b.T                  # transponha (troque linhas por colunas)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [358]:
b.sum()

21

### Caixa de sessão interativa 13: Operações com variáveis indexadas

In [ ]:
import numpy as np

In [359]:
a = np.array([1,2,3])                # variável indexada 1D
b = np.array([[1,2,3],[4,5,6]])      # variável indexada 2D
b

array([[1, 2, 3],
       [4, 5, 6]])

In [360]:
a ** 2                    # todos os elementos elevados a 2

array([1, 4, 9])

In [361]:
2 ** a                   # 2 elevado a cada elemento de 'a'

array([2, 4, 8])

In [362]:
a - 1                    # subtraia 1 de todos os elementos

array([0, 1, 2])

In [363]:
a * b                         # 'a' vezes cada linha de 'b'

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [364]:
a ** b                    # potenciação elemento-a-elemento

array([[  1,   4,  27],
       [  1,  32, 729]])

In [365]:
a + b                    # adicione 'a' a cada linha de 'b'

array([[2, 4, 6],
       [5, 7, 9]])

### Caixa de sessão interativa 14: Criação de matrizes e operações básicas

In [366]:
a = [[1,2],[3,4]]        # crie uma lista de listas
a = np.matrix(a)         # converta a lista em matriz
a

matrix([[1, 2],
        [3, 4]])

In [367]:
a[0,1]                   # primeira linha, segunda coluna

2

In [368]:
a + a                    # soma usual (elemento a elemento)

matrix([[2, 4],
        [6, 8]])

In [369]:
a * a                    # multiplicação usual de matrizes

matrix([[ 7, 10],
        [15, 22]])

In [370]:
a.diagonal()             # diagonal principal da matriz

matrix([[1, 4]])

In [371]:
a[:,1]                   # fatia (todas as linhas, coluna 2)

matrix([[2],
        [4]])

In [372]:
a.transpose()            # matriz transposta (ou use 'a.T')

matrix([[1, 3],
        [2, 4]])